### ISSUE TITLE
Does it matter if I use the old version to train or test?

### ISSUE THREAD

**Issue by George-Zhuang** [xingyul/stereobj-1m#1]
Dear authors,

I sincerely appreciate your efforts to make this dataset publicly available! 

I happen to notice that the dataset link in Dropbox is updating.  Does it matter if I use the old version to train or test? I downloaded it on  April 6.

Waiting for your kind reply.

**Comment by xingyul** [comment]
Hi @George-Zhuang, thanks for raising the concern. We uploaded the last file (`val_label_merged.json`) to the shared folder on Mar 15. If you completed the downloading on Apr 6, you should be good to go. However, you can also check the md5 of the downloaded files and compare them with our md5 to see if the files you downloaded are correct.

**Comment by George-Zhuang** [comment]
Thanks for your prompt response! I will check the md5 as you suggest.

Notably, I also found that the Dropbox link that you shared encounters a 404 error. I would appreciate it if you could check it.

Have a nice day!

**Comment by xingyul** [comment]
@George-Zhuang I have no problem accessing the directory. Could you access Dropbox in general? It is possible that you will need to use VPN to access Dropbox.

**Comment by George-Zhuang** [comment]
Thanks a lot for your help and great work. 

Now I can get access to the link smoothly, but actually I did have the VPN to access Dropbox. I think it may be because of the Dropbox policy for my generating excessive traffic.

Thanks again for your generous advice!
