### ISSUE TITLE
How to visualize pose?

### ISSUE THREAD

**Issue by jnauticus** [xingyul/stereobj-1m#3]
where do you get `import viz_object_in_image` ? I would like to visualize the pose and possibly with a bounding cube.

I am able to get Rotational and Translation and the pose matrix. (3,4) for 3 keypoints.

**Comment by xingyul** [comment]
Sorry, that part of the code, i.e. `viz_object_in_image `, is not supposed to be released. I have removed it from the code.

**Comment by xingyul** [comment]
Hi @jnauticus , I provided the example scripts for visualizing the pose, including rendering projected object keypoints, rendering normalized coordinate maps and instance masks, in the code. Please check out commits bc2bbe2 and 190848d for more details.
